---
title: "Assignment 1"
author: "Gabriel Odom"
date: "8/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise Set 1

1. Create an object called `myAge` that holds your age *in months*. Hint: the multiplication operator in R is `"*"`.
2. Using the object `myAge`, approximate the number of days you've been alive. Use 30.44 days per month. Check this against your age in days on [Wolfram Alpha](https://www.wolframalpha.com/input/?i=days+since+september+20+1984). How many days off was your estimate?
3. Using the object `myAge`, find your decimal age. (Hint: the division operator is `"/"`).
4. Copy and Paste `MyAge` into the console and press `ENTER`. What happens? Why?



# Exercise Set 2

1. Five people start the newest diet craze. Their weights (in kg) before and after were $[78\ 72\ 78\ 79\ 105]$ and $[67\ 65\ 79\ 70\ 93]$, respectively. Store these two vectors as `wtBefore` and `wtAfter`, respectively. Find the total
   weight lost, the average weight lost, and the weight lost per person.
2. Create the following vectors using the `rep()` and `seq()` functions:
    a) the first non-negative integer powers of 2
    b) 1, 1.5, 2, 2.5, ..., 12
    c) 1, 8, 27, 64, ..., 1000
    d) 1, -1/2, 1/3, -1/4, ..., -1/100
    e) 1, 0, 3, 0, 5, 0, 7, 0, ..., 0, 49
    f) 1, 3, 6, 10, 15, ..., 210 (Hint: `?cumsum`)
    g) 1, 2, 2, 3, 3, 3, ..., 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 (Hint: `?rep`)
3. (ADVANCED) Approximate the function $\log(1 - x)$ at $x = 0.25$ via polynomial expansion. Let $n = 5,\ 10,\ 50,\ 100$, and use the Taylor-MacLaurin series for the natural logarithm (shown below) to calculate the residuals for each specified value of $n$:
\[
\log(1 - x) := - \lim_{n \to \infty} \sum \limits_{j = 1}^n \frac{x ^ j}{j}.
\]
   
   
# Exercise Set 3

1. Create a vector of the months of the year and store it in an object called `mons`.
2. You would like to discard the first three months, so you type `mons[-1:3]`. What happened? Why should you type instead?
3. Find a method to use the `length()` function to find the last four entries of *any* atomic vector. Apply this to find the last four months of the year, as stored in `mons`.
4. Logically subset the uppercase vector of English letters in the following ways:
    a) Type `LETTERS` and press `ENTER`. What is your guess to find the lower case letters?
    b) Create a vector of the first 12 upper-case English letters
    c) Create a vector of the 1st, 3rd, 5th, 7th, ..., 25th English letters
    d) Create a vector of the consonants. (Hint: it may be easier to find the letters that are *not* one of the vowels)